FROM golang:1.26.3-alpine AS builder

RUN apk add --no-cache git build-base

WORKDIR /go/src/github.com/ory/hydra

COPY go.mod go.sum ./
COPY internal/httpclient/go.* ./internal/httpclient/

RUN go mod download

COPY . .
RUN CGO_ENABLED=0 go build -buildvcs=false -ldflags="-X 'github.com/ory/hydra/v2/driver/config.Version=2.3.2'" -o /usr/bin/hydra .

#########################

FROM alpine:3

RUN <<HEREDOC
    apk add --no-cache --upgrade ca-certificates

    # Add a user/group for nonroot with a stable UID + GID. Values are from nonroot from distroless
    # for interoperability with other containers.
    addgroup --system --gid 65532 nonroot
    adduser --system --uid 65532 \
      --gecos "nonroot User" \
      --home /home/nonroot \
      --ingroup nonroot \
      --shell /sbin/nologin \
      nonroot
HEREDOC

COPY --from=builder /usr/bin/hydra /usr/bin/hydra

USER nonroot

ENTRYPOINT ["hydra"]
CMD ["serve", "all"]
